name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: forcefield utilities Tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
        python-version: ["3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        name: Checkout Branch

      - name: Install Mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-dev.yml
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install Package
        run: python -m pip install -e .

      - name: Run Tests (OS -> ${{ matrix.os }} / Python -> ${{ matrix.python-version }})
        run: |
          python -m pytest -v --color yes forcefield_utilities/tests --cov
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  bleeding-edge-test:
    if: github.event.pull_request.draft == false
    name: Bleeding Edge mosdef Tests for ffutils
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        name: Checkout Branch / Pull Request

      - name: Install Mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment-dev.yml
          extra-specs: |
            python=3.8

      - name: Clone GMSO
        run: |
          git clone https://github.com/mosdef-hub/gmso.git

      - name: Update Environment with mbuild/foyer/ffutils Dependencies
        run: |
          micromamba update --name gmso-dev --file gmso/environment-dev.yml

      - name: Install Packages from Source
        run: |
          pip install -e gmso
          pip install -e .

      - name: Run Bleeding Edge Tests
        run: |
          python -m pytest -v --color yes --pyargs forcefield_utilities
